export const SHOW_DOT_LOADER = "SHOW_DOT_LOADER";
export const START_SUBMISSION_LOADER = "START_SUBMISSION_LOADER";
export const STOP_SUBMISSION_LOADER = "STOP_SUBMISSION_LOADER";
export const GET_SUBMISSION_DETAIL = "GET_SUBMISSION_DETAIL";
export const POST_SUBMISSION_DETAIL = "POST_SUBMISSION_DETAIL";
