// export const SHOW_DOT_LOADER = "SHOW_DOT_LOADER";

// Submission Detail Actions
export const START_SUBMISSION_LOADER = "START_SUBMISSION_LOADER";
export const STOP_SUBMISSION_LOADER = "STOP_SUBMISSION_LOADER";
export const GET_SUBMISSION_DETAIL = "GET_SUBMISSION_DETAIL";
export const POST_SUBMISSION_DETAIL = "POST_SUBMISSION_DETAIL";
export const UPDATE_SUBMISSION_DETAIL = "UPDATE_SUBMISSION_DETAIL";

// Site Dashboard Actions
export const GET_SITE_DASHBOARD = "GET_SITE_DASHBOARD";
export const GET_SITE_METAS = "GET_SITE_METAS";
export const GET_SITE_SUBMISSIONS = "GET_SITE_SUBMISSIONS";
export const GET_SITE_DOCUMENTS = "GET_SITE_DOCUMENTS";
export const GET_SITE_LOGS = "GET_SITE_LOGS";
export const GET_SITE_FORMS = "GET_SITE_FORMS";
export const GET_RECENT_PICTURES = "GET_RECENT_PICTURES";
export const GET_SUBSITES = "GET_SUBSITES";
export const SHOW_DOT_LOADER = "SHOW_DOT_LOADER";
export const SHOW_DASHBOARD_LOADERS = "SHOW_DASHBOARD_LOADERS";
export const UPDATE_SITE_LOGO = "UPDATE_SITE_LOGO";
