// export const SHOW_DOT_LOADER = "SHOW_DOT_LOADER";

// Submission Detail Actions
export const START_SUBMISSION_LOADER = "START_SUBMISSION_LOADER";
export const STOP_SUBMISSION_LOADER = "STOP_SUBMISSION_LOADER";
export const GET_SUBMISSION_DETAIL = "GET_SUBMISSION_DETAIL";
export const POST_SUBMISSION_DETAIL = "POST_SUBMISSION_DETAIL";
export const UPDATE_SUBMISSION_DETAIL = "UPDATE_SUBMISSION_DETAIL";
export const TOGGLE_NULL_SUBMISSIONS_ANSWER = "TOGGLE_NULL_SUBMISSIONS_ANSWER";

// Site Dashboard Actions
export const GET_SITE_DASHBOARD = "GET_SITE_DASHBOARD";
export const GET_SITE_METAS = "GET_SITE_METAS";
export const GET_SITE_SUBMISSIONS = "GET_SITE_SUBMISSIONS";
export const GET_SITE_DOCUMENTS = "GET_SITE_DOCUMENTS";
export const GET_SITE_LOGS = "GET_SITE_LOGS";
export const GET_SITE_FORMS = "GET_SITE_FORMS";
export const GET_RECENT_PICTURES = "GET_RECENT_PICTURES";
export const GET_SUBSITES = "GET_SUBSITES";
export const SHOW_DOT_LOADER = "SHOW_DOT_LOADER";
export const SHOW_DASHBOARD_LOADERS = "SHOW_DASHBOARD_LOADERS";
export const UPDATE_SITE_LOGO = "UPDATE_SITE_LOGO";
// export const SITE_DASHBOARD_ERR = "SITE_DASHBOARD_ERR";
// export const SITE_METAS_ERR = "SITE_METAS_ERR";
// export const SITE_SUBMISSIONS_ERR = "SITE_SUBMISSIONS_ERR";
// export const SITE_DOCUMENTS_ERR = "SITE_DOCUMENTS_ERR";
// export const SITE_PICTURES_ERR = "SITE_PICTURES_ERR";
// export const SITE_LOGS_ERR = "SITE_LOGS_ERR";

//Project Dashbaord Actions
export const GET_PROJECT_DASHBOARD = "GET_PROJECT_DASHBOARD";
export const GET_PROJECT_METAS = "GET_PROJECT_METAS";
export const GET_PROJECT_SUBMISSIONS = "GET_PROJECT_SUBMISSIONS";
export const GET_PROJECT_DOCUMENTS = "GET_PROJECT_DOCUMENTS";
export const GET_PROJECT_LOGS = "GET_PROJECT_LOGS";
export const GET_REGION_DATA = "GET_REGION_DATA";
export const GET_PROGRESS_TABLE_DATA = "GET_PROGRESS_TABLE_DATA";
export const GET_SURVEY_FORM = "GET_SURVEY_FORM";
// // export const GET_SUBSITES = "GET_SUBSITES";
// export const SHOW_DOT_LOADER = "SHOW_DOT_LOADER";
export const SHOW_PROJECT_DASHBOARD_LOADERS = "SHOW_PROJECT_DASHBOARD_LOADERS";
export const UPDATE_PROJECT_LOGO = "UPDATE_PROJECT_LOGO";

//Team Dashboard Actions
export const GET_TEAM_DASHBOARD = "GET_TEAM_DASHBOARD";
export const SHOW_TEAM_DASHBOARD_LOADERS = "SHOW_TEAM_DASHBOARD_LOADERS";
export const POST_PACKAGE_SUBSCRIBE = "POST_PACKAGE_SUBSCRIBE";

// User Document Actions
export const GET_USER_DOCUMENT = "GET_USER_DOCUMENT";

//Site Team Users
export const GET_TEAM_USERS = "GET_TEAM_USERS";

//Project List
export const GET_PROJECT_LIST = "GET_PROJECT_LIST";

// Project User List
export const GET_PROJECT_USER = "GET_PROJECT_USER";

//Project Log
 export const GET_LOGS ="GET_LOGS";

 //Teams
 export const GET_TEAMS = "GET_TEAMS";
 